// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type eventsTestDataSet int

const (
	eventTestDataSetDefault eventsTestDataSet = iota
	eventTestDataSetAll
	eventTestDataSetNone
)

func TestLogsBuilderAppendLogRecord(t *testing.T) {
	observedZapCore, _ := observer.New(zap.WarnLevel)
	settings := receivertest.NewNopSettings(receivertest.NopType)
	settings.Logger = zap.New(observedZapCore)
	lb := NewLogsBuilder(loadLogsBuilderConfig(t, "all_set"), settings)

	rb := lb.NewResourceBuilder()
	rb.SetMysqlInstanceEndpoint("mysql.instance.endpoint-val")
	res := rb.Emit()

	// append the first log record
	lr := plog.NewLogRecord()
	lr.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
	lr.Attributes().PutStr("type", "log")
	lr.Body().SetStr("the first log record")

	// append the second log record
	lr2 := plog.NewLogRecord()
	lr2.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
	lr2.Attributes().PutStr("type", "event")
	lr2.Body().SetStr("the second log record")

	lb.AppendLogRecord(lr)
	lb.AppendLogRecord(lr2)

	logs := lb.Emit(WithLogsResource(res))
	assert.Equal(t, 1, logs.ResourceLogs().Len())

	rl := logs.ResourceLogs().At(0)
	assert.Equal(t, 1, rl.ScopeLogs().Len())

	sl := rl.ScopeLogs().At(0)
	assert.Equal(t, ScopeName, sl.Scope().Name())
	assert.Equal(t, lb.buildInfo.Version, sl.Scope().Version())

	assert.Equal(t, 2, sl.LogRecords().Len())

	attrVal, ok := sl.LogRecords().At(0).Attributes().Get("type")
	assert.True(t, ok)
	assert.Equal(t, "log", attrVal.Str())

	assert.Equal(t, pcommon.ValueTypeStr, sl.LogRecords().At(0).Body().Type())
	assert.Equal(t, "the first log record", sl.LogRecords().At(0).Body().Str())

	attrVal, ok = sl.LogRecords().At(1).Attributes().Get("type")
	assert.True(t, ok)
	assert.Equal(t, "event", attrVal.Str())

	assert.Equal(t, pcommon.ValueTypeStr, sl.LogRecords().At(1).Body().Type())
	assert.Equal(t, "the second log record", sl.LogRecords().At(1).Body().Str())
}
func TestLogsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		eventsSet   eventsTestDataSet
		resAttrsSet eventsTestDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			eventsSet:   eventTestDataSetAll,
			resAttrsSet: eventTestDataSetAll,
		},
		{
			name:        "none_set",
			eventsSet:   eventTestDataSetNone,
			resAttrsSet: eventTestDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: eventTestDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: eventTestDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			timestamp := pcommon.Timestamp(1_000_001_000)
			traceID := [16]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
			spanID := [8]byte{0, 1, 2, 3, 4, 5, 6, 7}
			ctx := trace.ContextWithSpanContext(context.Background(), trace.NewSpanContext(trace.SpanContextConfig{
				TraceID:    trace.TraceID(traceID),
				SpanID:     trace.SpanID(spanID),
				TraceFlags: trace.FlagsSampled,
			}))
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			lb := NewLogsBuilder(loadLogsBuilderConfig(t, tt.name), settings)

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultEventsCount := 0
			allEventsCount := 0
			defaultEventsCount++
			allEventsCount++
			lb.RecordDbServerQuerySampleEvent(ctx, timestamp, AttributeDbSystemNameMysql, "mysql.current_schema-val", "mysql.sql_text-val", "mysql.digest-val", "mysql.digest_text-val", 18, 17.100000, 12, 15.100000, 16.100000, 15.100000, 19, 15, 19, 22, 28, 18, 24, 17, 23, 16, 15, 15, 19, 24, "mysql.processlist_user-val", "mysql.processlist_host-val", "mysql.processlist_db-val")

			rb := lb.NewResourceBuilder()
			rb.SetMysqlInstanceEndpoint("mysql.instance.endpoint-val")
			res := rb.Emit()
			logs := lb.Emit(WithLogsResource(res))

			if tt.expectEmpty || ((tt.name == "default" || tt.name == "filter_set_include") && defaultEventsCount == 0) {
				assert.Equal(t, 0, logs.ResourceLogs().Len())
				return
			}

			assert.Equal(t, 1, logs.ResourceLogs().Len())
			rl := logs.ResourceLogs().At(0)
			assert.Equal(t, res, rl.Resource())
			assert.Equal(t, 1, rl.ScopeLogs().Len())
			lrs := rl.ScopeLogs().At(0).LogRecords()
			if tt.eventsSet == eventTestDataSetDefault {
				assert.Equal(t, defaultEventsCount, lrs.Len())
			}
			if tt.eventsSet == eventTestDataSetAll {
				assert.Equal(t, allEventsCount, lrs.Len())
			}
			validatedEvents := make(map[string]bool)
			for i := 0; i < lrs.Len(); i++ {
				switch lrs.At(i).EventName() {
				case "db.server.query_sample":
					assert.False(t, validatedEvents["db.server.query_sample"], "Found a duplicate in the events slice: db.server.query_sample")
					validatedEvents["db.server.query_sample"] = true
					lr := lrs.At(i)
					assert.Equal(t, timestamp, lr.Timestamp())
					assert.Equal(t, pcommon.TraceID(traceID), lr.TraceID())
					assert.Equal(t, pcommon.SpanID(spanID), lr.SpanID())
					attrVal, ok := lr.Attributes().Get("db.system.name")
					assert.True(t, ok)
					assert.Equal(t, "mysql", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.current_schema")
					assert.True(t, ok)
					assert.Equal(t, "mysql.current_schema-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.sql_text")
					assert.True(t, ok)
					assert.Equal(t, "mysql.sql_text-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.digest")
					assert.True(t, ok)
					assert.Equal(t, "mysql.digest-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.digest_text")
					assert.True(t, ok)
					assert.Equal(t, "mysql.digest_text-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.end_event_id")
					assert.True(t, ok)
					assert.EqualValues(t, 18, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.timer_start")
					assert.True(t, ok)
					assert.Equal(t, 17.100000, attrVal.Double())
					attrVal, ok = lr.Attributes().Get("mysql.uptime")
					assert.True(t, ok)
					assert.EqualValues(t, 12, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.timer_end")
					assert.True(t, ok)
					assert.Equal(t, 15.100000, attrVal.Double())
					attrVal, ok = lr.Attributes().Get("mysql.timer_wait")
					assert.True(t, ok)
					assert.Equal(t, 16.100000, attrVal.Double())
					attrVal, ok = lr.Attributes().Get("mysql.lock_time")
					assert.True(t, ok)
					assert.Equal(t, 15.100000, attrVal.Double())
					attrVal, ok = lr.Attributes().Get("mysql.rows_affected")
					assert.True(t, ok)
					assert.EqualValues(t, 19, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.rows_sent")
					assert.True(t, ok)
					assert.EqualValues(t, 15, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.rows_examined")
					assert.True(t, ok)
					assert.EqualValues(t, 19, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.select_full_join")
					assert.True(t, ok)
					assert.EqualValues(t, 22, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.select_full_range_join")
					assert.True(t, ok)
					assert.EqualValues(t, 28, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.select_range")
					assert.True(t, ok)
					assert.EqualValues(t, 18, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.select_range_check")
					assert.True(t, ok)
					assert.EqualValues(t, 24, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.select_scan")
					assert.True(t, ok)
					assert.EqualValues(t, 17, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.sort_merge_passes")
					assert.True(t, ok)
					assert.EqualValues(t, 23, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.sort_range")
					assert.True(t, ok)
					assert.EqualValues(t, 16, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.sort_rows")
					assert.True(t, ok)
					assert.EqualValues(t, 15, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.sort_scan")
					assert.True(t, ok)
					assert.EqualValues(t, 15, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.no_index_used")
					assert.True(t, ok)
					assert.EqualValues(t, 19, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.no_good_index_used")
					assert.True(t, ok)
					assert.EqualValues(t, 24, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("mysql.processlist_user")
					assert.True(t, ok)
					assert.Equal(t, "mysql.processlist_user-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.processlist_host")
					assert.True(t, ok)
					assert.Equal(t, "mysql.processlist_host-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("mysql.processlist_db")
					assert.True(t, ok)
					assert.Equal(t, "mysql.processlist_db-val", attrVal.Str())
				}
			}
		})
	}
}
