# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases
#
# For the OpenTelemetry Collector Contrib official distribution sources, check
# https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib

dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  version: 0.123.0-dev
  output_path: ./cmd/otelcontribcol

extensions:
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.123.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.123.0
receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.123.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver v0.123.0
connectors:
providers:
# When using `make genotelcontribcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# Contrib modules.
replaces:
