# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases
#
# For the OpenTelemetry Collector Contrib official distribution sources, check
# https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib

dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  version: 0.129.0-dev
  output_path: ./cmd/otelcontribcol

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.129.1-0.20250630174123-18b3b578b0b3

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.129.1-0.20250630174123-18b3b578b0b3

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver v0.129.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.35.1-0.20250630174123-18b3b578b0b3
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.35.1-0.20250630174123-18b3b578b0b3
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.35.1-0.20250630174123-18b3b578b0b3
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.35.1-0.20250630174123-18b3b578b0b3
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.35.1-0.20250630174123-18b3b578b0b3
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/aesprovider v0.129.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/s3provider v0.129.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/secretsmanagerprovider v0.129.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/googlesecretmanagerprovider v0.129.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/vaultprovider v0.129.0
# When using `make genotelcontribcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# Contrib modules.
replaces:
